require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle'
    - 'bin/bundle'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - "spec/**/*"

Style/NumericLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
