require:  
  - rubocop-rails  
  - rubocop-rspec  
  
AllCops:  
  Exclude:  
    - 'vendor/bundle'  
  
Style/StringLiterals:  
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  