require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle'
    - 'bin/bundle'
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - "spec/**/*"

Style/NumericLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Layout/LineLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
